spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    url: /event-manager-openapi.yaml

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

logging:
  level:
    org:
      hibernate:
        type: TRACE