spring:
  application:
    name: event-manager-app

  profiles:
    active: kafka

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      cache-ttl-expiration-minutes: 30
      cache-event-key-prefix: "event:"

springdoc:
  swagger-ui:
    url: /event-manager-openapi.yaml

security:
  jwt:
    secret-key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"

server:
  error:
    include-stacktrace: never
    include-message: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      apache:
        catalina:
          core:
            ApplicationHttpRequest: ERROR

event:
  status:
    cron: "0 */3 * * * *"
